### ISSUE TITLE
hook.java

### ISSUE THREAD

**Issue by rikijha** [executeautomation/SeleniumWithCucucumber#36]
[ERROR] /C:/Users/Dell/.jenkins/workspace/BasicFreeStyle/src/test/java/steps/Hook.java:[34,59] illegal escape character
please add back lash

**Comment by pradipydesai** [comment]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Program Files (x86)/Jenkins/workspace/BasicFreestyle/src/test/java/steps/Hook.java:[34,59] illegal escape character
[ERROR] /C:/Program Files (x86)/Jenkins/workspace/BasicFreestyle/src/test/java/steps/Hook.java:[34,64] illegal escape character
[INFO] 2 errors

**Comment by colmeabhi** [comment]
illegal escape character add double backslash
