### ISSUE TITLE
"var" type not found? What am I missing?

### ISSUE THREAD

**Issue by ashwinbangalore** [executeautomation/SeleniumWithCucucumber#40]
What am I missing with this?

_[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project CucumberBasics: Compilation failure
[ERROR] /f:/gitprojects/SeleniumWithCucucumber/src/test/java/Base/ExtentReportUtil.java:[39,9] cannot find symbol
[ERROR]   symbol:   class var
[ERROR]   location: class Base.ExtentReportUtil
[ERROR]
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE_

**Comment by kasm2015** [comment]
Hello owner, could you please help us resolve the above reported issue???

**Comment by kasm2015** [comment]
> What am I missing with this?
> 
> _[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project CucumberBasics: Compilation failure [ERROR] /f:/gitprojects/SeleniumWithCucucumber/src/test/java/Base/ExtentReportUtil.java:[39,9] cannot find symbol [ERROR] symbol: class var [ERROR] location: class Base.ExtentReportUtil [ERROR] [ERROR] -> [Help 1] [ERROR] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging. [ERROR] [ERROR] For more information about the errors and possible solutions, please read the following articles: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException Build step 'Invoke top-level Maven targets' marked build as failure Finished: FAILURE_

Hello Ashwin,

replace var with File , it will work.

Thanks,
Syed Maqbul

**Comment by srikanthmca999** [comment]
after replaceing var with file also getting same error. Could you please help me out. below is the error.

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/Pipeline_Job/src/main/java/com/ea/Main.java:[34,9] cannot find symbol
  symbol:   class var
