### ISSUE TITLE
Getting "lambda expressions are not supported in -source 1.5" error at line no.73 in Main.java

### ISSUE THREAD

**Issue by isirajmunir** [executeautomation/SeleniumWithCucucumber#84]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Program Files (x86)/Jenkins/workspace/DemoFreestyleProject/src/main/java/com/ea/Main.java:[73,61] lambda expressions are not supported in -source 1.5
  (use -source 8 or higher to enable lambda expressions)
[ERROR] /C:/Program Files (x86)/Jenkins/workspace/DemoFreestyleProject/src/main/java/com/ea/Main.java:[118,50] method references are not supported in -source 1.5
  (use -source 8 or higher to enable method references)
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.426 s
[INFO] Finished at: 2020-03-18T17:29:09+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project CucumberBasics: Compilation failure: Compilation failure: 
[ERROR] /C:/Program Files (x86)/Jenkins/workspace/DemoFreestyleProject/src/main/java/com/ea/Main.java:[73,61] lambda expressions are not supported in -source 1.5
[ERROR]   (use -source 8 or higher to enable lambda expressions)

**Comment by flyeagle7268** [comment]
Hey - have fixed this issue? I am getting the same error, I am using Maven 3.6.3 and jdk 1.8

**Comment by Aforzzz** [comment]
Try this by updating source and target in Maven:
-Dmaven.compiler.source=8 -Dmaven.compiler.target=8

Jenkins->Advanced(from Maven Build section)-MAVEN_OPTS>

**Comment by executeautomation** [comment]
It all fixed now @flyeagle7268  @Aforzzz  and @isirajmunir !
